export const icons = {
  0: "arrows",
  1: "badge",
  2: "flask",
  3: "boot",
  4: "cactus",
  5: "cowskull",
  6: "dreamcatcher",
  7: "gallow",
  8: "horse",
  9: "horseshoe",
  10: "native",
  11: "pickaxe",
  12: "pistol",
  13: "saloon",
  14: "sheriff",
  15: "tomahawk",
  16: "-wagon",
  17: "wantedposter",
};
